### ISSUE TITLE
Crash slice bounds out of rang

### ISSUE THREAD

**Issue by dr4gn3l** [bitmagnet-io/bitmagnet#45]
**Have you checked the roadmap on the website, and existing issues, before opening a dupllcate issue?**
Yes

**Describe the bug**
bitmagnet crash with panic : 
```

panic: runtime error: slice bounds out of range [:49152] with capacity 38184

goroutine 5492610 [running]:
github.com/bitmagnet-io/bitmagnet/internal/metainfo/metainforequester.readAllPieces({0x935b360, 0xc000774590}, 0x9528)
        /mnt/podman-volume/bitmagnet/bitmagnet-io/internal/metainfo/metainforequester/requester.go:262 +0x445
github.com/bitmagnet-io/bitmagnet/internal/metainfo/metainforequester.requester.Request.func1()
        /mnt/podman-volume/bitmagnet/bitmagnet-io/internal/metainfo/metainforequester/requester.go:89 +0x1ae
created by github.com/bitmagnet-io/bitmagnet/internal/metainfo/metainforequester.requester.Request in goroutine 5492132
        /mnt/podman-volume/bitmagnet/bitmagnet-io/internal/metainfo/metainforequester/requester.go:67 +0x2e7

```
**To Reproduce**
Just wait a torrent with a lot of pieces I guess

**Expected behavior**
Not crash

**General (please complete the following information):**

- Bitmagnet version: v0.0.7
- OS and version: Ubuntu

**Comment by mgdigital** [comment]
Hi @dr4gn3l , this is fixed in the linked PR which will be merged shortly.
